INSERT INTO vocabs(id, word, interpretation, example_sen) value (1, 'grand', 'a.宏伟大，壮丽的，重大的', 'The museum that we visit is very grand.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (2, 'invade', 'v. 侵入，侵略，侵袭', 'When Balrogs invade the ship, you better avoid them. ');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (3, 'acid', 'n. 酸，酸性物质 a. 酸的；尖刻的', 'Aluminum is the main factor limiting plant growth on acid soil.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (4, '1acknowledge', 'v. 承认；致谢', '“Yeah, we’re playing the merit game,” acknowledges Tom Lancaster, associate dean for undergraduate education.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (5, 'balcony', 'n. 阳台', 'You can see the sea from our balcony.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (6, 'calculate', 'vt. 计算，核算', 'He must calculate the probability of failure.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (7, 'calendar', 'n. 日历，月历', 'Chinese New Year ,which is tied to the lunar cycle ,is one of the most celebrated holidays on the Chinese calendar.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (8, 'optimistic', 'a. 乐观', 'The man is quite optimistic about human nature.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (9, 'optional', 'a. 可以任选的，非强制的', 'Some courses in college are required while others are optional.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (10, 'outstanding', 'a. 杰出的，突出的，显著的', 'She made outstanding contributions to children’s education.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (11, 'export', ' n. 出口（物） v. 出口，输出', 'We export to many countries.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (12, 'import', 'n. 进口（物） v. 进口，输入', 'importing low-price prescription drugs from Canada');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (13, 'impose', 'vt. 把...加强(on)；采用，利用', 'You ought not to impose your thoughts on others.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (14, 'religion', 'n. 宗教，宗教信仰', 'He deceived them under the cloak of religion.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (15, 'religious', 'a. 宗教的', 'And Taoism is a religious sect.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (16, 'victim', 'n. 牺牲品，受害者', 'Scientists have devised a way to determine roughly where a person has lived using a strand(缕) of hair , a technique that could help track the movements of criminal suspects or unidentified murder victims .');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (17, 'video', 'n. 电视，视频 a. 电视的，录像的', 'Applying for artistic merit scholarships usually requires that students submit a portfolio(选辑)of some sort, whether that includes a collection of artwork, a recording of a musical performance or a video of them dancing.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (18, 'videotape', 'n. 录像磁带 v. 把...录在录像带上', 'When the children were 2, researchers videotaped them at home in free-play sessions with both parents, ____all of their speech.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (19, 'offend', 'v. 冒犯，触犯', 'He was offended by her unreasonable quarrel.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (20, 'bother', 'v. 打搅，麻烦', 'A survey found an overwhelming pessimism about privacy, with 60 percent of respondents saying they feel their privacy is “slipping away, and that bothers me.”');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (21, 'interfere', 'v. 干涉，干扰，妨碍', 'This is my life, no one can interfere.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (22, 'internal', 'a. 内部的，国内的', 'If we do not confront and overcome these internal fears and doubts, if we protect ourselves too much, then we cease to grow.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (23, 'beforehand', 'ad. 预先，事先', 'Rooms booked beforehand can be discounted by up to 50%.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (24, 'beforehand', 'ad. 预先，事先', 'Rooms booked beforehand can be discounted by up to 50%.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (25, 'radiation', 'n. 放射物，辐射', 'The use of radiation disinfection could solve some sticky problems.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (26, 'radical', 'a.根本的；激进的', 'They wish to adopt more radical methods.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (27, 'range', 'n. 幅度，范围 v. （在某范围内）变动', 'I needed to present the full range of duties, responsibilities and expectations to all candidates (2009年6月英语四级考试真题)');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (28, 'wonder', 'n. 惊奇，奇迹 v. 想知道，对...感到疑惑', 'In the late 19th century, Jules Verne, the master of science fiction, foresaw many of the technological wonders that are ________ today. (2006年6月17日大学英语四级(CET-4)真题试卷(A卷))');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (29, 'Isolate', ' vt. 使隔离，使孤立', 'These conditions are increasingly observable around the world. For instance, cultures that were previously isolated and homogeneous(同种类的) ,such as Japan, Denmark and Greece (45)_______.( 2008年12月大学英语四级考试)');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (30, 'issue', 'n. 问题，争论点；发行，（报刊）一期', 'Retailers who’re responsive and friendly are more likely to smooth over issues than those who aren’t so friendly.( 2008年12月大学英语四级考试真题)');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (31, 'hollow', ' a. 空的，中空的，空虚道', 'This is a hollow tree.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (32, 'hook', 'n. 钩 vt. 钩住', 'I hooked his foot when he passed me and he staggered but did not fall.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (33, 'adequate', 'a. 适当地；足够', 'The panda is an endangered species, which means that it is very likely to become ________ without adequate protection.（2006年6月17日大学英语四级(CET-4)真题试卷(A卷)）');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (34, 'adhere', 'vi. 粘附，附着；遵守，坚持', 'We adhered to our original plan of swimming in spite of the bad weather.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (35, ' ban', 'vt. 取缔，禁止', 'The police lifted the ban against parking in the street.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (36, 'capture', 'vt. 俘虏，捕获', 'They captured this city from the enemy last week.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (37, 'valid', 'a. 有效的，有根据的；正当的', 'Each of these philosophies is valid and, it has to be said, my son loves visiting his aunt’s house. （2008年12月大学英语四级考试真题）');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (38, 'valley', 'n. 山谷，峡谷', 'In a mountain valley of Spain（2006年6月17日大学英语四级(CET-4)真题试卷(A卷)）');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (39, 'consistent', 'a. 坚固定；一致的，始终如一的', 'Her parents’ consistent moral support （2006年6月17日大学英语四级(CET-4)真题试卷(A卷)）');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (40, 'continuous', 'a. 继续的，连续（不断）的', 'Firstly, no accomplishment can be achieved in a short time, and success asks for continuous industrious work and efforts.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (41, 'continual', 'a. 不断地，频繁的', 'Continual conflict among city-states caused the eventual decline of Greek civilization');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (42, 'explode', 'v. 爆炸；爆发；激增', 'Something was ready to explode inside of her because she could not make people understand her.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (43, 'exploit', 'v. 剥削；利用，开采', 'China make a great effort to develop marine enterprise, exploit and protect ocean.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (44, 'explore', 'v. 勘探', 'To explore strategies for lowering production costs （2008年6月大学英语四级考试真题）');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (45, 'explosion', 'n. 爆炸；爆发；激增', 'If only the explosion had not happened!');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (46, 'explosive', 'a. 爆炸的；极易引起争论的', 'That is explosive news. One of my colleagues admires her.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (47, ' remote', 'a. 遥远的，偏僻的', 'And ever since, I have never hesitated to head for even the most remote of places, without guides or even ____ bookings, confident that somehow I will manage. (2008年6月大学英语四级考试真题)');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (48, 'removal', 'n. 除去，消除', 'It is also ideal for water removal.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (49, 'render', 'vt. 使得，致使', 'They could not resist any more and decided to render up the city.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (50, 'precaution', 'n. 预防，防备，警惕', 'The bank takes another precaution as well.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (51, 'idle', 'a. 懒散的，无所事事的', 'An idle man never succeeds in anything.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (52, ' identify', 'vt. 认出，鉴定', 'You’ll move one step closer to your ideal work life if you identify how much risk you are willing to take and the sacrifices you are willing to make. (2007年6月23日大学英语四级(CET-4)真题试卷(A卷))');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (53, 'poverty', 'n. 贫穷', 'We need economic growth unless we condemn the world’s poor to their present poverty and freeze everyone else’s living standards. ( 2008年6月大学英语四级考试真题)');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (54, ' resistant', 'a. (to) 抵抗的，抗...的，耐...的', 'But it can get rid of fat resistant to traditional methods of losing weight.');
INSERT INTO vocabs(id, word, interpretation, example_sen) value (55, 'resolve', 'vt. 解决；决定，决意', 'To resolve the dilemma in the health-care system (2006年6月17日大学英语四级(CET-4)真题试卷(A卷))');
